[package]
name = "rust_project_management"
version = "0.1.0"
authors = ["ler <mielkedtyler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.2"
iced = "0.2.0"
